import { ProjectInput } from './project.model';

/**
 * Starter projects, generated from the author's public GitHub repositories.
 *
 * Real repository names, descriptions, languages and dates — nothing invented.
 * Technologies, topics and keywords are derived from each repository's
 * language and name. Covers are omitted so they fall back to GitHub's
 * generated social preview.
 *
 * Seeded only when projects.json does not exist. Use "Import from GitHub" in
 * admin to pull fresh data, which matches on repository URL and never
 * duplicates these.
 */
export const SEED_PROJECTS: ProjectInput[] = [
  {
    title: 'AWS Demo Project',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/AWS_Demo_Project',
    demoUrl: '',
    technologies: ['typescript', 'aws', 'docker', 'jenkins'],
    topics: ['devops'],
    keywords: ['ci-cd', 'deployment'],
    tags: [],
    year: '2026',
    startDate: '2026-07-18',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Bachelor Mess Manager',
    description:
      'Manage bachelor messes efficiently by creating groups, inviting members, recording meals, tracking expenses, and calculating monthly costsâ€”all in one place.',
    repoUrl: 'https://github.com/saidul-islam-rajib/Bachelor-Mess-Manager',
    demoUrl: '',
    technologies: ['typescript'],
    topics: ['productivity'],
    keywords: ['management'],
    tags: [],
    year: '2026',
    startDate: '2026-07-11',
    status: 'completed',
    featured: false,
  },
  {
    title: 'BcsExamPlatform',
    description:
      'The primary purpose of this app is to help student and bcs candidates',
    repoUrl: 'https://github.com/saidul-islam-rajib/BcsExamPlatform',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['education'],
    keywords: ['exam-platform'],
    tags: [],
    year: '2026',
    startDate: '2026-02-23',
    status: 'completed',
    featured: false,
  },
  {
    title: 'nopCommerce',
    description:
      'This repository is just for learning purpose. This repo code is originally collected from nopCommerce default public src',
    repoUrl: 'https://github.com/saidul-islam-rajib/nopCommerce',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['backend'],
    keywords: ['ecommerce'],
    tags: ['learning'],
    year: '2026',
    startDate: '2026-01-14',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Portfolio',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/Portfolio',
    demoUrl: 'https://portfolio-two-mauve-26.vercel.app',
    technologies: ['typescript'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2026',
    startDate: '2023-06-17',
    status: 'completed',
    featured: false,
  },
  {
    title: 'backend blog',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/backend-blog',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2025',
    startDate: '2025-02-24',
    status: 'completed',
    featured: false,
  },
  {
    title: 'admin blog',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/admin-blog',
    demoUrl: '',
    technologies: ['typescript'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2025',
    startDate: '2025-01-30',
    status: 'completed',
    featured: false,
  },
  {
    title: 'frontend blog',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/frontend-blog',
    demoUrl: '',
    technologies: ['html', 'css'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2025',
    startDate: '2025-02-24',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Authentication',
    description: 'Authenticated user will able to login/register',
    repoUrl: 'https://github.com/saidul-islam-rajib/Authentication',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net', 'jwt'],
    topics: ['security'],
    keywords: ['authentication'],
    tags: [],
    year: '2025',
    startDate: '2024-06-06',
    status: 'completed',
    featured: true,
  },
  {
    title: 'Auth',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/Auth',
    demoUrl: '',
    technologies: ['typescript', 'jwt'],
    topics: ['security'],
    keywords: ['authentication'],
    tags: [],
    year: '2025',
    startDate: '2025-02-01',
    status: 'completed',
    featured: false,
  },
  {
    title: 'PersonalBlogBackend',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/PersonalBlogBackend',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2025',
    startDate: '2024-11-19',
    status: 'completed',
    featured: true,
  },
  {
    title: 'ECommerce',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/ECommerce',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['backend'],
    keywords: ['ecommerce'],
    tags: [],
    year: '2024',
    startDate: '2024-11-26',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Portfolio Backend',
    description: 'Personal blog',
    repoUrl: 'https://github.com/saidul-islam-rajib/Portfolio-Backend',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['web'],
    keywords: ['blog', 'portfolio'],
    tags: [],
    year: '2024',
    startDate: '2024-05-29',
    status: 'completed',
    featured: true,
  },
  {
    title: 'Dinner Host',
    description: 'just for learning purpose',
    repoUrl: 'https://github.com/saidul-islam-rajib/Dinner_Host',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['backend'],
    keywords: ['booking'],
    tags: ['learning'],
    year: '2024',
    startDate: '2024-02-18',
    status: 'completed',
    featured: true,
  },
  {
    title: 'E Commerce',
    description: 'Full stack e-commerce website',
    repoUrl: 'https://github.com/saidul-islam-rajib/E-Commerce',
    demoUrl: '',
    technologies: ['javascript'],
    topics: ['backend'],
    keywords: ['ecommerce'],
    tags: [],
    year: '2024',
    startDate: '2024-06-07',
    status: 'completed',
    featured: true,
  },
  {
    title: 'task manager',
    description:
      'A basic task-manager platform(created just for learning purpose)',
    repoUrl: 'https://github.com/saidul-islam-rajib/task-manager',
    demoUrl: '',
    technologies: ['typescript'],
    topics: ['productivity'],
    keywords: ['management'],
    tags: ['learning'],
    year: '2024',
    startDate: '2024-05-22',
    status: 'completed',
    featured: true,
  },
  {
    title: 'Dinner Hosting Platform',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/Dinner_Hosting_Platform',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['backend'],
    keywords: ['booking'],
    tags: [],
    year: '2023',
    startDate: '2023-12-23',
    status: 'completed',
    featured: false,
  },
  {
    title: 'CleanArchitecture',
    description: 'just for learning purpose',
    repoUrl: 'https://github.com/saidul-islam-rajib/CleanArchitecture',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['architecture'],
    keywords: ['clean-architecture'],
    tags: ['learning'],
    year: '2023',
    startDate: '2023-12-18',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Aspnet MVC Crud',
    description: '',
    repoUrl: 'https://github.com/saidul-islam-rajib/Aspnet_MVC_Crud',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net'],
    topics: ['backend'],
    keywords: ['crud'],
    tags: [],
    year: '2023',
    startDate: '2023-11-29',
    status: 'completed',
    featured: false,
  },
  {
    title: 'AspnetMicroservices',
    description: 'AspnetMicroservices project using .net web api, c#',
    repoUrl: 'https://github.com/saidul-islam-rajib/AspnetMicroservices',
    demoUrl: '',
    technologies: ['c#', 'asp.net core', '.net', 'microservices', 'docker'],
    topics: ['architecture'],
    keywords: ['microservices'],
    tags: [],
    year: '2023',
    startDate: '2023-07-04',
    status: 'completed',
    featured: false,
  },
  {
    title: 'FullStackCrudOperation',
    description: 'For this project; I have used angular and .net6',
    repoUrl: 'https://github.com/saidul-islam-rajib/FullStackCrudOperation',
    demoUrl: '',
    technologies: ['typescript'],
    topics: ['backend'],
    keywords: ['crud'],
    tags: [],
    year: '2022',
    startDate: '2022-11-07',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Console Application',
    description: 'This is a basic game for Black Jack Game using CPP',
    repoUrl: 'https://github.com/saidul-islam-rajib/Console_Application',
    demoUrl: '',
    technologies: ['c++'],
    topics: ['desktop'],
    keywords: ['desktop-app'],
    tags: [],
    year: '2022',
    startDate: '2022-03-22',
    status: 'completed',
    featured: false,
  },
  {
    title: 'Desktop application',
    description:
      'This is a basic notepad application, developed without any OOP concent.',
    repoUrl: 'https://github.com/saidul-islam-rajib/Desktop_application',
    demoUrl: '',
    technologies: ['python'],
    topics: ['desktop'],
    keywords: ['desktop-app'],
    tags: [],
    year: '2022',
    startDate: '2022-03-22',
    status: 'completed',
    featured: false,
  },
];
